import { Router } from 'express';
import PDFDocument from 'pdfkit';
import {
  HDate,
  HebrewCalendar,
  flags,
} from '@hebcal/core';

export const router = Router();

// POST /pdf/calendar  body: { year, month, il }
router.post('/calendar', (req, res) => {
  const { year = new Date().getFullYear(), month = new Date().getMonth() + 1, il = false } = req.body;

  const options = {
    year: Number(year),
    month: Number(month),
    isHebrewYear: false,
    il: Boolean(il),
    mask: flags.HOLIDAYS | flags.ROSH_CHODESH | flags.PARSHA_HASHAVUA |
          flags.LIGHT_CANDLES | flags.YOM_TOV_ENDS,
  };
  const events = HebrewCalendar.calendar(options);

  const doc = new PDFDocument({ size: 'LETTER', margin: 40 });
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader(
    'Content-Disposition',
    `attachment; filename="calendar-${year}-${String(month).padStart(2, '0')}.pdf"`
  );
  doc.pipe(res);

  // Title
  const monthName = new Date(year, month - 1, 1).toLocaleString('en-US', { month: 'long' });
  doc.fontSize(20).text(`${monthName} ${year} – Jewish Calendar`, { align: 'center' });
  doc.moveDown(0.5);
  doc.fontSize(10).text(`Generated by 613 Suite`, { align: 'center' });
  doc.moveDown(1);

  // Table header
  const cols = ['Date', 'Hebrew Date', 'Event (EN)', 'Event (HE)'];
  const colWidths = [80, 100, 180, 130];
  let x = 40;
  const headerY = doc.y;
  doc.font('Helvetica-Bold').fontSize(9);
  cols.forEach((col, i) => {
    doc.text(col, x, headerY, { width: colWidths[i] });
    x += colWidths[i];
  });
  doc.moveDown(0.3);
  doc.moveTo(40, doc.y).lineTo(570, doc.y).stroke();
  doc.moveDown(0.3);

  // Rows
  doc.font('Helvetica').fontSize(8);
  events.forEach(ev => {
    const rowY = doc.y;
    if (rowY > 720) { doc.addPage(); }
    const rowData = [
      ev.getDate().greg().toISOString().slice(0, 10),
      ev.getDate().toString(),
      ev.render('en'),
      ev.render('he'),
    ];
    x = 40;
    rowData.forEach((cell, i) => {
      doc.text(cell || '', x, doc.y, { width: colWidths[i], lineBreak: false });
      x += colWidths[i];
    });
    doc.moveDown(0.8);
  });

  doc.end();
});

// POST /pdf/zmanim  body: { lat, lon, tzid, date, days }
router.post('/zmanim', async (req, res) => {
  const { lat = 40.67, lon = -73.94, tzid = 'America/New_York', date, days = 7 } = req.body;
  const startDate = date ? new Date(date) : new Date();

  const doc = new PDFDocument({ size: 'LETTER', margin: 40 });
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="zmanim.pdf"`);
  doc.pipe(res);

  doc.fontSize(18).text('Zmanim Table', { align: 'center' });
  doc.fontSize(10).text(`Lat: ${lat}, Lon: ${lon} | ${tzid}`, { align: 'center' });
  doc.moveDown(1);

  for (let d = 0; d < Number(days); d++) {
    const current = new Date(startDate);
    current.setDate(current.getDate() + d);
    const hdate = new HDate(current);
    doc.font('Helvetica-Bold').fontSize(10)
      .text(`${current.toDateString()} / ${hdate.toString()}`);
    doc.font('Helvetica').fontSize(8);
    // Simplified row – actual zmanim would require SunCalc
    doc.text(`  Sunrise / Sunset calculations require @hebcal/noaa (see API endpoint)`);
    doc.moveDown(0.5);
  }

  doc.end();
});
